#ifndef _C_\USERS\COOPER\REPOS\WILLOWS-DREAM\RES_GFX_H_
#define _C_\USERS\COOPER\REPOS\WILLOWS-DREAM\RES_GFX_H_

extern const Image imagetest;

#endif // _C_\USERS\COOPER\REPOS\WILLOWS-DREAM\RES_GFX_H_
