theme: jekyll-minimal-theme
title: Willow's Dream
author:
    name: Willow's Dream Team
description: An Action-RPG homebrew ROM game developed for the Sega Genesis/Mega Drive.

path: /willows-dream
url: http://dcooperdalrymple.github.io/willows-dream

markdown: kramdown

sass:
    sass_dir: css
    style: expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false
